2019-06-02 08:48:22,844 : INFO : Machine : Mission Pinball Framework Core Engine v0.52.2
2019-06-02 08:48:22,845 : INFO : Machine : Command line arguments: {'production': False, 'no_load_cache': False, 'consoleloglevel': 20, 'text_ui': True, 'create_config_cache': True, 'mpfconfigfile': '/usr/local/lib/python3.5/dist-packages/mpf/mpfconfig.yaml', 'loglevel': 15, 'force_platform': None, 'mc_file_name': None, 'force_assets_load': False, 'bcp': True, 'pause': False, 'no_sound': False, 'logfile': 'logs/2019-06-02-08-48-22-mpf-bench.log', 'jsonlogging': False, 'syslog_address': None, 'configfile': ['config.yaml']}
2019-06-02 08:48:22,845 : INFO : Machine : MPF path: /usr/local/lib/python3.5/dist-packages/mpf
2019-06-02 08:48:22,846 : INFO : Machine : Machine path: /home/murray/pinball/machines/test
2019-06-02 08:48:22,846 : INFO : Machine : Platform: linux
2019-06-02 08:48:22,846 : INFO : Machine : Python executable location: /usr/bin/python3
2019-06-02 08:48:22,846 : INFO : Machine : Python version: 3.5.3 (64-bit)
2019-06-02 08:48:22,846 : INFO : Machine : Machine config file #1: config.yaml
2019-06-02 08:48:22,848 : WARNING : ConfigProcessor : Cache file not found: /tmp/f9b476974087260b844455b1771539d9.mpf_cache
2019-06-02 08:48:22,848 : INFO : ConfigProcessor : Loading config from file /usr/local/lib/python3.5/dist-packages/mpf/mpfconfig.yaml.
2019-06-02 08:48:23,124 : INFO : ConfigProcessor : Loading config: /usr/local/lib/python3.5/dist-packages/mpf/mpfconfig.yaml
2019-06-02 08:48:23,147 : INFO : ConfigProcessor : Loading config from file /home/murray/pinball/machines/test/config/config.yaml.
2019-06-02 08:48:23,151 : ERROR : root : Error found in file /home/murray/pinball/machines/test/config/config.yaml: Version mismatch. Expected: #config_version=5 Actual:  Files: /home/murray/pinball/machines/test/config/config.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mpf/file_interfaces/yaml_interface.py", line 197, in load
    expected_version_str, version_str, filename))
AssertionError: Version mismatch. Expected: #config_version=5 Actual:  Files: /home/murray/pinball/machines/test/config/config.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mpf/commands/game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/machine.py", line 175, in __init__
    self._load_config()
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/machine.py", line 444, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "/usr/local/lib/python3.5/dist-packages/mpf/file_interfaces/yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file /home/murray/pinball/machines/test/config/config.yaml: Version mismatch. Expected: #config_version=5 Actual:  Files: /home/murray/pinball/machines/test/config/config.yaml
