2019-06-02 08:47:11,702 : INFO : Machine : Mission Pinball Framework Core Engine v0.52.2
2019-06-02 08:47:11,703 : INFO : Machine : Command line arguments: {'pause': False, 'force_platform': None, 'no_sound': False, 'jsonlogging': False, 'force_assets_load': False, 'production': False, 'loglevel': 15, 'bcp': True, 'mpfconfigfile': '/usr/local/lib/python3.5/dist-packages/mpf/mpfconfig.yaml', 'create_config_cache': True, 'mc_file_name': None, 'text_ui': True, 'no_load_cache': False, 'logfile': 'logs/2019-06-02-08-47-11-mpf-bench.log', 'consoleloglevel': 20, 'syslog_address': None, 'configfile': ['config.yaml']}
2019-06-02 08:47:11,704 : INFO : Machine : MPF path: /usr/local/lib/python3.5/dist-packages/mpf
2019-06-02 08:47:11,704 : INFO : Machine : Machine path: /home/murray/pinball/machines/test
2019-06-02 08:47:11,704 : INFO : Machine : Platform: linux
2019-06-02 08:47:11,704 : INFO : Machine : Python executable location: /usr/bin/python3
2019-06-02 08:47:11,704 : INFO : Machine : Python version: 3.5.3 (64-bit)
2019-06-02 08:47:11,704 : INFO : Machine : Machine config file #1: config.yaml
2019-06-02 08:47:11,706 : WARNING : ConfigProcessor : Cache file not found: /tmp/f9b476974087260b844455b1771539d9.mpf_cache
2019-06-02 08:47:11,706 : INFO : ConfigProcessor : Loading config from file /usr/local/lib/python3.5/dist-packages/mpf/mpfconfig.yaml.
2019-06-02 08:47:11,981 : INFO : ConfigProcessor : Loading config: /usr/local/lib/python3.5/dist-packages/mpf/mpfconfig.yaml
2019-06-02 08:47:12,004 : INFO : ConfigProcessor : Loading config from file /home/murray/pinball/machines/test/config/config.yaml.
2019-06-02 08:47:12,028 : INFO : ConfigProcessor : Loading config: /home/murray/pinball/machines/test/config/config.yaml
2019-06-02 08:47:12,032 : ERROR : root : Could not find file /home/murray/pinball/machines/test/config/machine-config.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/file_manager.py", line 80, in load
    file = FileManager.locate_file(filename)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/file_manager.py", line 53, in locate_file
    raise FileNotFoundError("File not found: {}".format(filename))
FileNotFoundError: File not found: /home/murray/pinball/machines/test/config/machine-config.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mpf/commands/game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/machine.py", line 175, in __init__
    self._load_config()
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/machine.py", line 444, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/config_processor.py", line 163, in _load_config_file_and_return_loaded_files
    subconfig, subsubfiles = self._load_config_file_and_return_loaded_files(full_file, config_type)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "/usr/local/lib/python3.5/dist-packages/mpf/core/file_manager.py", line 83, in load
    raise IOError("Could not find file {}".format(filename))
OSError: Could not find file /home/murray/pinball/machines/test/config/machine-config.yaml
